<?php echo View::getContent(); ?>

<script type="text/javascript">
    Event.observe(window, 'load',function(){
        $('codare').focus();
    });
 </script>

<div id='botones' align='right'>
    <table>
        <tr>
            <td><?php echo Tag::linkTo(Router::getController()."/nuevo",Tag::image("nuevo.png","title: Nuevo","class: boton")) ?></td>
            <td><?php echo Tag::image("buscar.png","title: Buscar","onclick: $('form').submit();","class: boton") ?></td>
        </tr>
    </table>
</div>

<?php echo Tag::form(Router::getController()."/buscar","id: form","autocomplete: off"); ?>
    <div align='center'>
        <table align='center'>
            <tr>
                <td align="right"><b>Cod.Area:</b></td>
                <td colspan="2"><?php echo Tag::textUpperField("codare","size: 2","maxlength: 2") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Operacion:</b></td>
                <td align='left'><?php echo Tag::textUpperField("codope","size: 3","maxlength: 3") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Detalle:</b></td>
                <td align='left'><?php echo Tag::textUpperField("detalle","size: 30","maxlength: 35") ?></td>
            </tr>
        </table>
    </div>
 <?php echo Tag::endForm() ?>
