<?php if($botones){ ?>
<div id="botones" align="right">
    <table>
        <tr>
            <td><?php echo Tag::image("reporte.png","title: Reporte","class: boton","onclick: reporte()") ?></td>
            <td><?php echo Tag::linkTo(Router::getController()."/index",Tag::image("exit.png","title: Salir","class: boton")) ?></td>
        </tr>
    </table>
</div>
<?php }

$field = 2;

if(count($gener->items)>0){ ?>
<div id="consulta" align="center" style="width: 650px;">
    <table align="center" width="100%" cellpadding='0' cellspacing='1'>
        <thead>
            <tr>
                <th width="25px">Accion</th>
                <th width="25px">Cantidad</th>
                <!-- <th width="25px">Fecha</th>-->
            </tr>
        </thead>
        <?php $i=0; foreach($gener->items as $mgener){ ?>
            <tr class="td<?php echo $i%2+1 ?>">
                <?php if($mgener->getAccionDetalle() != '' || $mgener->getAccionDetalle() != FALSE){ ?>
                    <td align="center" width="25px"><?php echo strtoupper($mgener->getAccionDetalle()); ?></td>
                <?php }else{?>    
                    <td align="center" width="25px"><?php echo strtoupper($mgener->getAccion())."-> XXXXXXX"; ?></td>
                <?php }?>    
                <td align="center" width="25px"><?php echo $mgener->getId(); ?></td>
                <!--<td align="center" width="25px"><?php echo $mgener->getFecha(); ?></td>-->
            </tr>
        <?php $i++; } for($i=10-count($gener->items);$i>0;$i--){
            echo "<tr class='td".($i%2+1)."' height='25px'>";
            for($j=0;$j<$field;$j++) echo "<td></td>";
            echo "</tr>";
        } ?>
        <tr>
            <td colspan="<?php echo $field ?>" align="right" style="border: none;">
                <?php echo $html; ?>
            </td>
        </tr>
    </table>
</div>
<?php } else { ?>
    No hay Resultados para la b&uacute;squeda.
<?php } ?>
