<?php echo View::getContent(); ?>
<script type="text/javascript">
var val = new Validator();
Event.observe(window,'load',function(){
    mercurio05 = new Detail({
        view: 'capt_det',
        fields: ['codfir','cedula','nombre','cargo','email'],
        classTr: ['det_row1','det_row2'],
        empty: 'empty_msg'
    });
    $('codfir').focus();
    val.addField("codfir","text",null,{'alias': 'Firma','isNull': false});
    val.addField("cedula","text",null,{'alias': 'Cedula','isNull': false});
    val.addField("nombre","text",null,{'alias': 'Nombre','isNull': false});
    val.addField("cargo","text",null,{'alias': 'Cargo','isNull': false});
    val.addField("email","text",null,{'alias': 'Email','isNull': true});
});

function save(){
    if(!val.valide()){
        Messages.valide(val);
    } else {       
        error = false;
        for(i=1;i<=mercurio05.getNumRows();i++){
            if(mercurio05.getRow(i)['codasi']==$F('codasi')){
                if(!mercurio05.isEdit()){
                    Messages.display(Array("El registro ya existe"),"warning");
                    error=true;
                    $('codasi').value='';
                    $('codasi').focus();    
                }       
            }
        }
        if(!error){
            mercurio05.save({
                afterSave: function(){
                    new Effect.Fade('edit_msg',{queue: 'end', scope: 'detalle'});
                }
            });
            $('codasi').enable();  
            $('codasi').focus();  
        }
    }
}
function removeRow(row){
    mercurio05.remove(row,{
        beforeRemove: function(elem){
            if(mercurio05.isEdit(elem)){
                Messages.display(Array("El registro actual esta en edicion"),"warning");
                return false;
            }
        }
    });
    $('codasi').focus();
}

function edit(e){
    $('codasi').disable(); 
    mercurio05.edit(e,{
        beforeEdit: function(){
            if(mercurio05.isEdit()){
                Messages.display(Array("Hay un registro en edicion"),"warning");
                return false;
            }
        },
        afterEdit: function(){
            new Effect.Appear('edit_msg',{queue: 'end', scope: 'detalle'});
        },
    });
    $('numdoc').focus(); 
}

function cancel(){
    $('codasi').enable(); 
    mercurio05.cancelEdit();
    new Effect.Fade('edit_msg',{queue: 'end', scope: 'detalle'});
    $('codasi').focus();
}

</script>

<div id="botones" align="right">
    <table>
        <tr>
            <td><?php echo Tag::image("guardar.png","title: Guardar","onclick: $('form').submit();","class: boton") ?></td>
            <td><?php echo Tag::linkTo("mercurio05/index",Tag::image("exit.png","title: Cancelar","class: boton")) ?></td>
        </tr>
    </table>
</div>

<?php
 $width="850px";
 $rows=10;
 $field=4;
?>

<div>
    <table style="width: <?php echo $width ?>;">
        <tr>
            <td align="center" colspan="<?php echo $field ?>" height="30px">
                <div id="edit_msg" style="display: none; cursor: pointer; background-color: #DDFFDD" onclick="cancel();">
                    Registro en Edici&oacute;n (Click aqui para Cancelar)
                </div>
            </td>
        </tr>
        <tr>
            <td align="center"><?php echo Tag::select("codfir",$Mercurio03->find(),"using: codfir,detalle","onkeydown: saveIntro(event,this);","use_dummy: true") ?> </td>
            <td align="center"><?php echo Tag::textUpperField("cedula","maxlength: 10","size: 10","autocomplete: off","onkeydown: saveIntro(event,this);") ?> </td>
            <td align="center"><?php echo Tag::textUpperField("nombre","maxlength: 25","size: 20","autocomplete: off","onkeydown: saveIntro(event,this);") ?> </td>
            <td align="center"><?php echo Tag::textUpperField("cargo","maxlength: 25","size: 20","autocomplete: off","onkeydown: saveIntro(event,this);") ?> </td>
            <td align="center"><?php echo Tag::textUpperField("email","maxlength: 30","size: 25","autocomplete: off","onkeydown: saveIntro(event,this);") ?> </td>
            <td align="center" class="det_img"><?php echo Tag::image("Plus.png","title: Agregar Fila","onclick: save();") ?></td>
        </tr>
        <tr>
            <td align="center" class="titulos">Firma</td>
            <td align="center" class="titulos">Cedula</td>
            <td align="center" class="titulos">Nombre</td>
            <td align="center" class="titulos">Cargo</td>
            <td align="center" class="titulos">Email</td>
            <td>&nbsp;</td>
        </tr>
    </table>
</div>

<?php echo Tag::form("mercurio05/guardar", "id: form"); ?>
    <div id="capt_det" style="height: <?php echo ($rows*27)+($rows+2) ?>px;width: <?php echo $width ?>;">
        <table align="center" width="100%" cellpadding="0" cellspacing="1">
            <thead align="center">
                <tr id="empty_msg" style="display: <?php echo count($mercurio05)>0 ? 'none' : 'block' ?>;">
                    <td colspan="<?php echo $field ?>" align="center">No hay <?php echo $titulo; ?> que mostrar</td>
                </tr>
            </thead>
            <tbody>
        <?php if(!count($mercurio05)){ ?>
                <tr height="25px" ondblclick="edit(this);"  title="DobleClick para Editar">
                    <td class="codfir_" align="center" width="150px"></td>
                    <td class="cedula_" align="center" width="100px"></td>
                    <td class="nombre_" align="center" width="150px"></td>
                    <td class="cargo_" align="center" width="170px"></td>
                    <td class="email_" align="center" width="170px"></td>
                    <td class="det_img" align="center" width="40px"><?php echo Tag::image("Minus.png","title: Borrar Fila","onclick: removeRow(this.ancestors()[1])") ?></td>
                </tr>
        <?php } else {
                $i=0;
                foreach ($mercurio05 as $mmercurio05){ ?>
                <tr class="det_row<?php echo $i%2+1 ?>" height="25px" ondblclick="edit(this);"  title="DobleClick para Editar">
                    <td class="codfir_" align="center" width="150px"><?php echo Tag::hiddenField("codfir[]","value: {$mmercurio05->getCodfir()}") ?><?php echo $mmercurio05->getCodfir() ?></td>
                    <td class="cedula_" align="center" width="100px"><?php echo Tag::hiddenField("cedula[]","value: {$mmercurio05->getCedula()}") ?><?php echo $mmercurio05->getCedula() ?></td>
                    <td class="nombre_" align="center" width="150px"><?php echo Tag::hiddenField("nombre[]","value: {$mmercurio05->getNombre()}") ?><?php echo $mmercurio05->getNombre() ?></td>
                    <td class="cargo_" align="center" width="170px"><?php echo Tag::hiddenField("cargo[]","value: {$mmercurio05->getCargo()}") ?><?php echo $mmercurio05->getCargo() ?></td>
                    <td class="email_" align="center" width="170px"><?php echo Tag::hiddenField("email[]","value: {$mmercurio05->getEmail()}") ?><?php echo $mmercurio05->getEmail() ?></td>
                    <td class="det_img" align="center" width="40px"><?php echo Tag::image("Minus.png","title: Borrar Fila","onclick: removeRow(this.ancestors()[1])") ?></td>
                </tr>
        <?php $i++; } } ?>
            </tbody>
        </table>
    </div>
<?php echo Tag::endForm() ?>
