<?php echo View::getContent(); ?>
<script type="text/javascript">
var val = new Validator();
Event.observe(window,'load',function(){
    mercurio10 = new Detail({
        view: 'capt_det',
        fields: ['codare','codope','tipo','estado'],
        classTr: ['det_row1','det_row2'],
        empty: 'empty_msg'
    });
    $('codare').focus();
    val.addField("codare","select",null,{'alias': 'Area','isNull': false});
    val.addField("codope","select",null,{'alias': 'Operacion','isNull': false});
    val.addField("tipo","select",null,{'alias': 'tipo','isNull': false});
    val.addField("estado","select",null,{'alias': 'Estado','isNull': false});
});

function save(){
    if(!val.valide()){
        Messages.valide(val);
    } else {       
        error = false;
        for(i=1;i<=mercurio10.getNumRows();i++){
            if(mercurio10.getRow(i)['codare']==$F('codare') && mercurio10.getRow(i)['codope']==$F('codope')){
                if(!mercurio10.isEdit()){
                    Messages.display(Array("El registro ya existe"),"warning");
                    error=true;
                    $('codare').value='';
                    $('codare').focus();    
                }       
            }
        }
        if(!error){
            mercurio10.save({
                afterSave: function(){
                    new Effect.Fade('edit_msg',{queue: 'end', scope: 'detalle'});
                    actualizar_select();
                }
            });
            $('codare').enable();  
            $('codare').focus();  
        }
    }
}
function removeRow(row){
    mercurio10.remove(row,{
        beforeRemove: function(elem){
            if(mercurio10.isEdit(elem)){
                Messages.display(Array("El registro actual esta en edicion"),"warning");
                return false;
            }
        }
    });
    $('codare').focus();
}

function edit(e){
    $('codare').disable(); 
    var codope  = e.select("input")[1].value;;
    mercurio10.edit(e,{
        beforeEdit: function(){
            if(mercurio10.isEdit()){
                Messages.display(Array("Hay un registro en edicion"),"warning");
                return false;
            }
        },
        afterEdit: function(){
            new Effect.Appear('edit_msg',{queue: 'end', scope: 'detalle'});
            cargarOperaciones();
            $('codope').value = codope;
            actualizar_select();
        },
    });
    $('tipo').focus(); 
}

function cancel(){
    $('codare').enable(); 
    mercurio10.cancelEdit();
    actualizar_select();
    new Effect.Fade('edit_msg',{queue: 'end', scope: 'detalle'});
    $('codare').focus();
}

function cargarOperaciones(){
    new Ajax.Request(Utils.getKumbiaURL($Kumbia.controller+"/cargarOperaciones"), {
        asynchronous : false,
        parameters: {
            codare: $F('codare')
        },
        onSuccess: function(transport){
            response = transport.responseText.evalJSON();
            $('operacion_td').innerHTML = response;
            new Chosen($('codope'));
        },
        onFailure: function(transport){
            alert(transport.responseText);
        }
    });
}

</script>

<div id="botones" align="right">
    <table>
        <tr>
            <td><?php echo Tag::image("guardar.png","title: Guardar","onclick: $('form').submit();","class: boton") ?></td>
            <td><?php echo Tag::linkTo("mercurio10/index",Tag::image("exit.png","title: Cancelar","class: boton")) ?></td>
        </tr>
    </table>
</div>

<?php
 $width="850px";
 $rows=10;
 $field=4;
?>

<div>
    <table style="width: <?php echo $width ?>;">
        <tr>
            <td align="center" colspan="<?php echo $field ?>" height="30px">
                <div id="edit_msg" style="display: none; cursor: pointer; background-color: #DDFFDD" onclick="cancel();">
                    Registro en Edici&oacute;n (Click aqui para Cancelar)
                </div>
            </td>
        </tr>
        <tr>
            <td align="center"><?php echo Tag::select("codare",$Mercurio08->find(),"using: codare,detalle","onkeydown: saveIntro(event,this);","use_dummy: true","onchange: cargarOperaciones();") ?> </td>
            <td align="center" id='operacion_td'><?php echo Tag::selectStatic("codope",array(),"autocomplete: off","onkeydown: saveIntro(event,this);","use_dummy: true") ?> </td>
            <td align="center"><?php echo Tag::selectStatic("tipo",$Mercurio10->getTipoArray(),"autocomplete: off","onkeydown: saveIntro(event,this);","use_dummy: true") ?> </td>
            <td align="center"><?php echo Tag::selectStatic("estado",$Mercurio10->getEstadoArray(),"autocomplete: off","onkeydown: saveIntro(event,this);","use_dummy: true") ?> </td>
            <td align="center" class="det_img"><?php echo Tag::image("Plus.png","title: Agregar Fila","onclick: save();") ?></td>
        </tr>
        <tr>
            <td align="center" class="titulos">Area</td>
            <td align="center" class="titulos">Operacion</td>
            <td align="center" class="titulos">Tipo</td>
            <td align="center" class="titulos">Estado</td>
            <td>&nbsp;</td>
        </tr>
    </table>
</div>

<?php echo Tag::form("mercurio10/guardar", "id: form"); ?>
    <div id="capt_det" style="height: <?php echo ($rows*27)+($rows+2) ?>px;width: <?php echo $width ?>;">
        <table align="center" width="100%" cellpadding="0" cellspacing="1">
            <thead align="center">
                <tr id="empty_msg" style="display: <?php echo count($mercurio10)>0 ? 'none' : 'block' ?>;">
                    <td colspan="<?php echo $field ?>" align="center">No hay <?php echo $titulo; ?> que mostrar</td>
                </tr>
            </thead>
            <tbody>
        <?php if(!count($mercurio10)){ ?>
                <tr height="25px" ondblclick="edit(this);"  title="DobleClick para Editar">
                    <td class="codare_" align="center" width="150px"></td>
                    <td class="codope_" align="center" width="150px"></td>
                    <td class="tipo_" align="center" width="200px"></td>
                    <td class="estado_" align="center" width="100px"></td>
                    <td class="det_img" align="center" width="40px"><?php echo Tag::image("Minus.png","title: Borrar Fila","onclick: removeRow(this.ancestors()[1])") ?></td>
                </tr>
        <?php } else {
                $i=0;
                foreach ($mercurio10 as $mmercurio10){ ?>
                <tr class="det_row<?php echo $i%2+1 ?>" height="25px" ondblclick="edit(this);"  title="DobleClick para Editar">
                    <td class="codare_" align="center" width="150px"><?php echo Tag::hiddenField("codare[]","value: {$mmercurio10->getCodare()}") ?><?php echo $mmercurio10->getCodare() ?></td>
                    <td class="codope_" align="center" width="150px"><?php echo Tag::hiddenField("codope[]","value: {$mmercurio10->getCodope()}") ?><?php echo $mmercurio10->getCodope() ?></td>
                    <td class="tipo_" align="center" width="200px"><?php echo Tag::hiddenField("tipo[]","value: {$mmercurio10->getTipo()}") ?><?php echo $mmercurio10->getTipo() ?></td>
                    <td class="estado_" align="center" width="100px"><?php echo Tag::hiddenField("estado[]","value: {$mmercurio10->getEstado()}") ?><?php echo $mmercurio10->getEstado() ?></td>
                    <td class="det_img" align="center" width="40px"><?php echo Tag::image("Minus.png","title: Borrar Fila","onclick: removeRow(this.ancestors()[1])") ?></td>
                </tr>
        <?php $i++; } } ?>
            </tbody>
        </table>
    </div>
<?php echo Tag::endForm() ?>
