<?php if($botones){ ?>
<div id="botones" align="right">
    <table>
        <tr>
            <td><?php echo Tag::image("reporte.png","title: Reporte","class: boton","onclick: reporte()") ?></td>
            <td><?php echo Tag::linkTo(Router::getController()."/index",Tag::image("exit.png","title: Salir","class: boton")) ?></td>
        </tr>
    </table>
</div>
<?php }

$field = 4;

if(count($mercurio->items)>0){ ?>
<div id="consulta" align="center" style="width: 650px;">
    <table align="center" width="100%" cellpadding='0' cellspacing='1'>
        <thead>
            <tr>
                <th width="25px">Caja</th>
                <th width="25px">Nit</th>
                <th width="25px">Razon Social</th>
            </tr>
        </thead>
        <?php $i=0; foreach($mercurio->items as $mmercurio){ ?>
            <tr class="td<?php echo $i%2+1 ?>" ondblclick="window.location='<?php echo Core::getInstancePath()."/".Router::getActiveApplication()."/".Router::getController()."/editar/{$mmercurio->getCodcaj()}"?>'"height="25px" title="DobleClick para editar">
                <td align="center" width="20px"><?php echo $mmercurio->getCodcaj(); ?></td>
                <td align="center" width="200px"><?php echo $mmercurio->getNit(); ?></td>
                <td align="center" width="200px"><?php echo $mmercurio->getRazsoc(); ?></td>
                <td align="center" width="5px"><?php echo Tag::image("minus.png","title: Click para Borrar","onclick: borrar('{$mmercurio->getCodcaj()}')") ?></td>
            </tr>
        <?php $i++; } for($i=10-count($mercurio->items);$i>0;$i--){
            echo "<tr class='td".($i%2+1)."' height='25px'>";
            for($j=0;$j<$field;$j++) echo "<td></td>";
            echo "</tr>";
        } ?>
        <tr>
            <td colspan="<?php echo $field ?>" align="right" style="border: none;">
                <?php echo $html; ?>
            </td>
        </tr>
    </table>
</div>
<?php } else { ?>
    No hay Resultados para la b&uacute;squeda.
<?php } ?>
