<?php echo View::getContent(); ?>
<script>

function completar(id_,elem_){
  
    UI.Window.addMethods({
        CloseWinEmpresa: function(){
        this.destroy();
        }
    });

   manager = new UI.WindowManager({
      container: 'captura'
   });


    var ventana = new UI.Window({
            id: 'empresaWin',
            theme: 'leopard',
            //minimize: false,
            //maximize: false,
            ////resizable: false,
            close: 'CloseWinEmpresa',
            width: 350,
            height: 200, 
    });


    ventana.center().setHeader("Certificado de Retiro").show();
    ventana.activate();
    manager.register(ventana);
    
    new Ajax.Request(Utils.getKumbiaURL("mercurio36/formulario"), {
        parameters: {
            id: id_
        },
        asyncronous: false,
        onSuccess: function(transport){
            formu = transport.responseText.evalJSON();
            ventana.setContent(formu).show();

            val = new Validator();
            val.addField('fecret','date',null,{'alias': 'fecha de Retiro','isNull': false});

        },
        onFailure: function(transport){
            alert(transport.responseText);
        }
    });

  //  $$('.chosen-container').invoke('remove');
    //$$('select').invoke('show');

    id = id_;
    elem = elem_;
    //aprobar(id,elem);
return;
}

function rechazar(id,elem){
    var com = confirm("Seguro de Rechazar este retiro de Trabajador ?");
    if(com==false)return;
    elem = elem.up();
    new Ajax.Request(Utils.getKumbiaURL("mercurio36/rechazar"), {
      parameters: {
        id: id
      },
      onSuccess: function(transport){
        var response = transport.responseText.evalJSON();
        if(response['flag']==true){
          Messages.display(Array(response['msg']),"success");
          elem.remove();
        }else{
          Messages.display(Array(response['msg']),"warning");
        }
      },
      onFailure: function(transport){
        alert(transport.responseText);
      }
    });
 }

function aprobarF(){
    if(!val.valide()){
        Messages.valide(val);    
        return;
    } 
    var com = confirm("Seguro de Aprobar esta Empresa ?");
    if(com==false)return;
    
    elem = elem.up();
    parameters = new Array();
    parameters['id'] = id;

   new Ajax.Request(Utils.getKumbiaURL("mercurio36/aprobar"), {
      parameters: {
        id: id,
        fecret: $F('fecret')
      },

      onSuccess: function(transport){
        response = transport.responseText.evalJSON();
        if(response['flag']==true){
          Messages.display(Array(response['msg']),"success");
          elem.remove();
        }else{
          Messages.display(Array(response['msg']),"warning");
        }
      },

      onFailure: function(transport){
        alert(transport.responseText);
      }
    });
  }

</script>


<?php
  echo $html;
?>
