<?php echo View::getContent(); ?>

<script type="text/javascript">
    var val = new Validator();
    Event.observe(window, 'load',function(){
        val.addField("documento","number",null,{'alias': 'Usuario','isNull': false});
        val.addField("tipo","text",null,{'alias': 'Cedula','isNull': false});
        $('documento').disable();
    });

    function Guardar(){
        if(!val.valide()){
            Messagespro.valide(val);
        }else{
            $('form').submit();
        }
    }
    
 </script>

<div id='botones' align='right'>
    <table>
        <tr>
            <td><?php echo Tag::image("guardar.png","title: Guardar","onclick: Guardar();","class: boton") ?></td>
            <td><?php echo Tag::linkTo(Router::getController()."/index",Tag::image("exit.png","title: Cancelar","class: boton")) ?></td>
        </tr>
    </table>
</div>

<?php echo Tag::form(Router::getController()."/guardar","id: form","autocomplete: off"); ?>
    <div align='center'>
        <table align='center'>
            <tr>
                <td align="right"><b>Documento:</b></td>
                <td colspan="2"><?php echo Tag::numericField("documento") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Email:</b></td>
                <td align='left'><?php echo Tag::textField("email") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Tipo:</b></td>
                <td align='left'><?php echo Tag::selectStatic("tipo",array('T'=>'Afiliado','E'=>'Empresa','P'=>'Particular'),"use_dummy: true","disabled: disabled") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Agencia:</b></td>
                <td align='left'><?php echo Tag::selectStatic("agencia",array('1'=>'NEIVA','2'=>'GARZON','3'=>'PITALITO','4'=>'LA PLATA'),"use_dummy: true","class: form-control","disabled: disabled") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Pregunta 1:</b></td>
                <td align='left'><?php echo Tag::select("preg1",$Mercurio18->find(),'using: codigo,detalle',"use_dummy: true","class: form-control","disabled: disabled") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Respuesta 1:</b></td>
                <td align='left'><?php echo Tag::textField("resp1","disabled: disabled") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Pregunta 2:</b></td>
                <td align='left'><?php echo Tag::select("preg2",$Mercurio18->find(),'using: codigo,detalle',"use_dummy: true","class: form-control","disabled: disabled") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Respuesta 2:</b></td>
                <td align='left'><?php echo Tag::textField("resp2","disabled: disabled") ?></td>
            </tr>
        </table>
    </div>
 <?php echo Tag::endForm() ?>
