<script>
$(document).ready(function(){   
    if($("#mer19").val() == 0){
        modalPreg();
    }
});
modalPreg = function(){
    $('#modalPreguntas').modal('show');
}
function registrar(){
    $('#form').submit();
}
</script>
<?php echo View::getContent(); ?>
<?php echo Tag::hiddenField("mer19", "value: $mer19");?>
    <div class="modal fade" id="modalPreguntas" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document" style=" width: 60%">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title barra barra-center" id="myModalLabel">Guardar preguntas</h4>
                </div>
                <div class="modal-body">
                        <b>Asigne sus preguntas de seguridad.</b>
                </div>
                <div class="modal-footer">
                    <div style="width: 92%; margin-left: auto; margin-right: auto;";>
                        <?php echo Tag::form(Router::getController()."/preguntas","id: form","autocomplete: off","enctype: multipart/form-data"); ?>
                            <div class="form-group" style=" width: 100%">
                                <div class="col-sm-5" style="margin-top: 5px;">
                                    <label class="col-sm-12 control-label">Pregunta de Seguridad</label>
                                </div>
                                <div class="col-sm-5" style="margin-top: 5px;">
                                    <?php echo Tag::select("pregunta1",$Mercurio18->find(),"using: codigo,detalle","use_dummy: true","dummyText: Pregunta 1","class: form-control"); ?>
                                </div>
                                <div class="col-sm-5" style="margin-top: 5px;">
                                    <label class="col-sm-12 control-label">Respuesta</label>
                                </div>
                                <div class="col-sm-5" style="margin-top: 5px;">
                                    <?php echo Tag::textField("respuest1","placeholder: Respuesta 1","class: form-control") ?>
                                </div>
                                <div class="col-sm-5">
                                    <label class="col-sm-12 control-label">Pregunta de Seguridad</label>
                                </div>
                                <div class="col-sm-5" style="margin-top: 5px;">
                                    <?php echo Tag::select("pregunta2",$Mercurio18->find(),"using: codigo,detalle","use_dummy: true","dummyText: Pregunta 1","class: form-control"); ?>
                                </div>
                                <div class="col-sm-5" style="margin-top: 5px;">
                                    <label class="col-sm-12 control-label">Respuesta</label>
                                </div>
                                <div class="col-sm-5" style="margin-top: 5px;">
                                    <?php echo Tag::textField("respuest2","placeholder: Respuesta 2","class: form-control") ?>
                                </div>
                                <div class="col-sm-offset-1 col-sm-10" style=" text-align: center; margin-top: 5px;">
                                    <button type="button" class="btn btn-success btn-md" onclick="registrar()">Guardar</button>
                                </div>
                            </div>
                        <?php echo Tag::endForm(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
