<?php echo View::getContent(); ?>

<script type="text/javascript">

elem = '';
id  = '';
Event.observe(window,'load',function(){
    $('vista').setStyle({
        'width': '1000px',
        'marginLeft': '-40px'
      });
});

function completar(id_,elem_){
    UI.Window.addMethods({
        CloseWinTrabajador: function(){
        this.destroy();
        }
    });
   manager = new UI.WindowManager({
      container: 'captura'
   });
    var ventana = new UI.Window({
            id: 'trabajadorWin',
            theme: 'leopard',
            //minimize: false,
            //maximize: false,
            ////resizable: false,
            close: 'CloseWinTrabajador',
            width: 600,
            height: 231, 
    });
    ventana.center().setHeader("Certificado de aprobación").show();
    ventana.activate();
    manager.register(ventana);
    
    new Ajax.Request(Utils.getKumbiaURL("mercurio31/formulario"), {
        parameters: {
            id: id_
        },
        asyncronous: false,
        onSuccess: function(transport){
            formu = transport.responseText.evalJSON();
            ventana.setContent(formu).show();

            val = new Validator();
            val.addField('fecafi','date',null,{'alias': 'fecha de Afiliacion','isNull': false});
        },
        onFailure: function(transport){
            alert(transport.responseText);
        }
    });
    id = id_;
    elem = elem_;
return;

}

function aprobarF(){
    if(!val.valide()){
        Messages.valide(val);    
        return;
    } 
    var com = confirm("Seguro de Aprobar este Trabajador ?");
    if(com==false)return;
   new Ajax.Request(Utils.getKumbiaURL("mercurio31/aprobar"), {
      parameters: {
        id: id,
        agro: $F('agro'),
        //codcat: $F('codcat'),
        fecafi: $F('fecafi'),
        captra: $F('captra'),
        tipfor: $F('tipfor'),
        //observacion: $F('observacion')
      },

      onSuccess: function(transport){
        response = transport.responseText.evalJSON();
        if(response['flag']==true){
          $('trabajadorWin').remove();
          elem = elem.up();
          elem.remove();
          Messagespro.display(Array(response['msg']),"success");
        }else{
          Messagespro.display(Array(response['msg']),"warning");
        }
      },

      onFailure: function(transport){
        alert(transport.responseText);
      }
    });
  }


  function rechazar(id,elem){
    var com = confirm("Seguro de Rechazar este Trabajador ?");
    if(com==false)return;
    var motivo = prompt("Motivo de Rechazo?","");
    if(motivo=="" || motivo==null){
        alert("Debe digitar un Motivo");
        return;
    }
    elem = elem.up();
    new Ajax.Request(Utils.getKumbiaURL("mercurio31/rechazar"), {
      parameters: {
        id: id,
        motivo: motivo
      },
      onSuccess: function(transport){
        var response = transport.responseText.evalJSON();
        if(response['flag']==true){
          elem.remove();
          Messagespro.display(Array(response['msg']),"success");
        }else{
          Messagespro.display(Array(response['msg']),"warning");
        }
      },
      onFailure: function(transport){
        alert(transport.responseText);
      }
    });
  }

function verdoc(trab){
    UI.Window.addMethods({
        CloseWinEmpresa: function(){
            this.destroy();
        }
    });
   manager = new UI.WindowManager({
      container: 'captura'
   });
    var ventana = new UI.Window({
            id: 'empresaWin',
            theme: 'leopard',
            //minimize: false,
            //maximize: false,
            ////resizable: false,
            close: 'CloseWinEmpresa',
            width: 400,
            height: 470, 
    });
    ventana.center().setHeader("Documentación Trabajador No."+ trab).show();
    ventana.activate();
    manager.register(ventana);
    new Ajax.Request(Utils.getKumbiaURL("mercurio31/verdocumentos"),{
        parameters: {
           trabajador : trab,
        },
        
        onSuccess: function(transport){
            lista = transport.responseText.evalJSON();
            ventana.setContent(lista).show();
        },

        onFailure: function(transport){
            alert(transport.responseText);
        }    
    });
}
</script>

<?php
  echo $html;
?>
