<?php View::getContent(); ?>
<script>
$(document).ready(function(){   
    $('form').keypress(function(e){   
        if(e == 13){
            return false;
        }
    });
    $('input').keypress(function(e){
        if(e.which == 13){
            return false;
        }
    });
    $('[data-toggle="tooltip"]').tooltip();
    window.onbeforeunload = confirmaSalida;  
    flagSalida = false;
});
    buscar = function(){
        $("#form").validate({
            rules: {
                periodo: { required:true},
            },
        }); 
        var request  = $.ajax({
            type: "POST",
            url:Utils.getKumbiaURL("subsidio/giroEmp"),
            data: {
                periodo: $('#periodo').val()
            }
        });
        if(!$("#form").valid()){
            Messages.display("Faltan Campos por Digitar","error");
            return;
        }
        if($('#periodo').val().substring(4,6) == 00){
            $('#periodo').focus();
            Messages.display("Verifique que el periodo el mes sea diferente a 00","warning");
            return;
        }        
        request.done(function( transport ) {
            var response = jQuery.parseJSON(transport);
            $("#respuesta").html(response); 
        });
        request.fail(function( jqXHR, textStatus ) {
            Messages.display(response['msg'],"error");
        });
    }
    valper = function(){
        if($('#periodo').val().length <='3' || $('#periodo').val().length >='7'){
            Messages.display("El periodo ingresado no es valido, digite un periodo valido","warning");
            $('#periodo').val("");
            $('#periodo').focus();
        }if($('#periodo').val().substring(4,6) == 00){
            $('#periodo').focus();
            Messages.display("Verifique que el periodo el mes sea diferente a 00","warning");
            return;
        }
    }
</script>
<?php echo Tag::form(Router::getController()."/giroEmp","id: form","autocomplete: off","enctype: multipart/form-data"); ?>
<div style='height: 310px; max-height: auto;'>
    <table class="contenedor" style="margin: auto; border-collapse: separate; border-spacing: 5px;" width="95%">
        <tr style="padding= 2%" align="cedter">
            <td align='right' width="31%"><label>Periodo:</label></td>
            <td align='center' width="30%">
                <div class="input-group" >
                    <div class="input-group-addon"  ><span class="glyphicon glyphicon-info-sign" aria-hidden="true"  data-toggle="tooltip" title="El periodo inicial se utiliza con la union de año-mes"  ></span></div>
                        <?php echo Tag::numericField("periodo","class: form-control col-sm-10","style: margin-left: -3%; ","maxlength: 6","onchange: valper()"); ?>
                </div>
            </td>
            <td  width="200px"><?php echo Tag::Button("Consultar Giro",'class: btn btn-primary',"onclick: buscar();") ?></td>
        </tr>
        <tr>
            <td colspan="3">
                <table style="margin: auto; border-collapse: separate; border-spacing: 5px;" width="100%">
                    <tr>
                        <td id='respuesta'> </td>  
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
<?php echo Tag::endForm(); ?>
