<?php View::getContent(); ?>
<script>
    buscar = function(){
      if($F('anno') == ""){
        $('anno').focus();
        Messages.display("Por favor digite el a&ntilde;o por el cual se quiere buscar","warning");
        return;
      }else{
        var anno = $F('anno');
        new Ajax.Request(Utils.getKumbiaURL("subsidio/planilla"), {
          parameters: {
            anno: anno
          },
          onSuccess: function(transport){
            response = transport.responseText.evalJSON();
          $('consulta').innerHTML= response;  
           if(response == false){
                 Messages.display("El anno ingresado no existe, digite un anno valido","warning");
            }
          },
          onFailure: function(transport){
            alert(transport.responseText);
          }
        });
       }
    }
valano = function(){
    if($F('anno').length !='4'){
        Messages.display("El a$ntilde;o dingresado no es valido, digite un anno valido","warning");
        $('anno').value="";
        $('anno').focus();
    }
}
</script>
<?php echo Tag::form(Router::getController()."/planilla","id: form","autocomplete: off","enctype: multipart/form-data"); ?>
<div>
<table style="border-collapse: separate; border-spacing: 5px;" width="95%">
<tr>
    <td align="center">
        <table width="80%">
            <tr>
                <td align='right' width="31%"><label>A&ntilde;o:</label></td>
                <td align='center' width="110px"><?php echo Tag::numericField("anno","style: width: 100px; ","onchange: valano()","maxlength: 2"); ?></td>
                <td  width="200px"><?php echo Tag::Button("Consultar Giro",'class: submit','style: width: 200px; height: 24px;',"onclick: buscar();") ?></td>
            </tr>
            <tr>
                <td colspan="4" align="center">
                </td>
            </tr>
        </table>
    </td>
</tr>    
    <tr>
            <td id='consulta'> </td>  
    </tr>
</table>
</div>
<?php echo Tag::endForm(); ?>



<?php //View::getContent(); ?>
<?php //echo Tag::form(Router::getController()."/planilla_view"); ?>
