<?php echo View::getContent(); ?>

<script type="text/javascript">

elem = '';
id  = '';
Event.observe(window,'load',function(){
    $('vista').setStyle({
        'width': '1000px',
        'marginLeft': '-40px'
      });
});

function completar(id_,elem_){
  
    UI.Window.addMethods({
        CloseWinEmpresa: function(){
        this.destroy();
        }
    });

   manager = new UI.WindowManager({
      container: 'captura'
   });


    var ventana = new UI.Window({
            id: 'empresaWin',
            theme: 'leopard',
            //minimize: false,
            //maximize: false,
            ////resizable: false,
            close: 'CloseWinEmpresa',
            width: 680,
            height: 285, 
    });


    ventana.center().setHeader("Certificado de aprobación").show();
    ventana.activate();
    manager.register(ventana);
    
    new Ajax.Request(Utils.getKumbiaURL("mercurio34/formulario"), {
        asyncronous: false,
        onSuccess: function(transport){
            formu = transport.responseText.evalJSON();
            ventana.setContent(formu).show();
            val = new Validator();
            val.addField('giro','select',null,{'alias': 'Giro','isNull': false});
            val.addField('pago','select',null,{'alias': 'Pago','isNull': false});
            val.addField('numhij','text',null,{'alias': 'Numero de Hijos','isNull': false});
            val.addField('fecpre','date',null,{'alias': 'Fecha de  Presentacion','isNull': false});
            val.addField('fecasi','date',null,{'alias': 'Fecha de Afiliacion','isNull': false});
        },
        onFailure: function(transport){
            alert(transport.responseText);
        }
    });

  //  $$('.chosen-container').invoke('remove');
    //$$('select').invoke('show');

    id = id_;
    elem = elem_;
    //aprobar(id,elem);
return;

}

function aprobarF(){
    
    if(!val.valide()){
        Messages.valide(val);    
        return;
    }
    var com = confirm("Seguro de Aprobar este beneficiario?");
    if(com==false)return;
    

    parameters = new Array();
    parameters['id'] = id;

   $('form-completar').select("input","select").each(function(e){ 
           parameters[e.id]  = $(e.id).value;
   });
   if($F('fecasi')=="" || $F('tipfor')==""){
        Messagespro.display(Array('debe de digitar todos los valores'),"warning");
        return;
   }
    var fecha = new Date();
    var fecasi = new Date($F('fecasi'));
    fecha.setMonth(fecha.getMonth()-3);
    if(fecasi < fecha){
        Messagespro.display(Array('La fecha de Asignacion no puede ser menor a 3 meses'),"warning");
        return;
    }
    var fecha = new Date();
    var fecasi = new Date($F('fecasi'));
    fecha.setMonth(fecha.getMonth()+1);
    if(fecasi > fecha){
        Messagespro.display(Array('La fecha de Asignacion no puede ser mayor a 1 mes'),"warning");
        return;
    }
   new Ajax.Request(Utils.getKumbiaURL("mercurio34/aprobar"), {
      parameters: {
        id: id,
        //captra: $F('captra'),
        fecasi: $F('fecasi'),
        tipfor: $F('tipfor'),
        //observacion: $F('observacion')
      },

      onSuccess: function(transport){
        response = transport.responseText.evalJSON();
        if(response['flag']==true){
          $('empresaWin').remove();
          elem = elem.up();
          elem.remove();
          Messagespro.display(Array(response['msg']),"success");
        }else{
          Messagespro.display(Array(response['msg']),"warning");
        }
      },

      onFailure: function(transport){
        alert(transport.responseText);
      }
    });
  }
 
function rechazar(doc,elem){
    var com = confirm("Seguro de rechazar este Beneficiario?");
    if(com==false)return;
    var motivo = prompt("Motivo de Rechazo?","");
    if(motivo=="" || motivo==null){
        alert("Debe digitar un Motivo");
        return;
    }
    elem = elem.up();
    new Ajax.Request(Utils.getKumbiaURL("mercurio34/rechazar"), {
      parameters: {
        doc: doc,
        motivo: motivo
      },
      onSuccess: function(transport){
        var response = transport.responseText.evalJSON();
        if(response['flag']==true){
          elem.remove();
          console.log("hjkl");
          Messagespro.display(Array(response['msg']),"success");
        console.log("jhfdjk");
        }else{
          Messagespro.display(Array(response['msg']),"warning");
        }
      },
      onFailure: function(transport){
        alert(transport.responseText);
      }
    });
  }
function verdoc(benef){
    UI.Window.addMethods({
        CloseWinEmpresa: function(){
            this.destroy();
        }
    });
   manager = new UI.WindowManager({
      container: 'captura'
   });
    var ventana = new UI.Window({
            id: 'empresaWin',
            theme: 'leopard',
            //minimize: false,
            //maximize: false,
            ////resizable: false,
            close: 'CloseWinEmpresa',
            width: 400,
            height: 470, 
    });
    ventana.center().setHeader("Documentació beneficiario No".benf).show();
    ventana.activate();
    manager.register(ventana);
    new Ajax.Request(Utils.getKumbiaURL("mercurio34/verdocumentos"),{
        parameters: {

            nuevoBen : benef
        },
        
        onSuccess: function(transport){
            lista = transport.responseText.evalJSON();
            ventana.setContent(lista).show();
        },

        onFailure: function(transport){
            alert(transport.responseText);
        }    
    });
}

function info(id_,elem_){
    UI.Window.addMethods({
        CloseWinTrabajador: function(){
        this.destroy();
        }
    });
   manager = new UI.WindowManager({
      container: 'captura'
   });
    var ventana = new UI.Window({
            id: 'trabajadorWin',
            theme: 'leopard',
            close: 'CloseWinTrabajador',
            width: 800,
            height: 500, 
    });
    ventana.center().setHeader("Certificado de aprobación").show();
    ventana.activate();
    manager.register(ventana);
    
    new Ajax.Request(Utils.getKumbiaURL("mercurio34/info"), {
        parameters: {
            id: id_
        },
        asyncronous: false,
        onSuccess: function(transport){
            formu = transport.responseText.evalJSON();
            ventana.setContent(formu).show();

            val = new Validator();
            val.addField('fecafi','date',null,{'alias': 'fecha de Afiliacion','isNull': false});
        },
        onFailure: function(transport){
            alert(transport.responseText);
        }
    });
    id = id_;
    elem = elem_;
return;

}

</script>

<?php
	echo $html;
?>
