<!DOCTYPE html>
<html lang="es-CO">
 <head>
  <meta charset="utf-8">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="Sistemas y Soluciones Integradas S.A.S">
  <title>Servicio en linea - <?php echo Session::getDATA('title'); ?></title>
  <link rel="shorcut icon" href="<?php echo Core::getInstancePath()?>img/portal/ico_mercurio.ico" type="image/x-icon"> 
  <?php
  	echo Tag::getDocumentTitle();
    Tag::addJavascript('bootstrap/bootstrap-datepicker'); 
    Tag::addJavascript('bootstrap/Jqueryvalidation'); 
    Tag::addJavascript('portal/portalJQ'); 
    Tag::addJavascript('bootstrap/jquery.blockUI');
    Tag::addJavascript('portal/messages'); 
	Tag::addJavascript('core/base-source');
    Tag::addJavascript('bootstrap/bootstrap.min');
    Tag::addJavascript('bootstrap/jquery-2.1.4');
	echo Tag::getJavascriptLocation();
	echo Tag::javascriptSources();

  	//Tag::stylesheetLink('style');
  	//Tag::stylesheetLink('chosen/chosen');
  	Tag::stylesheetLink('portal/messages');
  	Tag::stylesheetLink('bootstrap/css/bootstrap.min');
  	Tag::stylesheetLink('bootstrap/css/carousel');
    Tag::stylesheetLink('bootstrap/css/datepicker');
    //Tag::stylesheetLink('portal/portal');
	echo Tag::stylesheetLinkTags();
    //echo Tag::stylesheetLink('themes/window/leopard');
    //echo Tag::stylesheetLink("calendar", true);
    //Tag::addJavascript('portal/portal');
    //echo Tag::addJavascriptFramework('prototype');
    //echo Tag::javascriptLibrary("framework/scriptaculous/window");
    //echo Tag::javascriptLibrary("framework/scriptaculous/effects");
    //echo Tag::javascriptLibrary("framework/scriptaculous/scriptaculous");
    //echo Tag::javascriptLibrary("framework/chosen");
    //echo Tag::javascriptLibrary("detalle");
    //echo Tag::javascriptLibrary("calendar");
    //echo Tag::javascriptLibrary("validator");
    //echo Tag::javascriptLibrary("event.simulate");
  ?>
 </head>
 <body>
  <?php View::getContent(); ?>
 </body>
</html>
