<?php echo View::getContent(); ?>
<script type="text/javascript">
var val = new Validator();
Event.observe(window,'load',function(){
    mercurio06 = new Detail({
        view: 'capt_det',
        fields: ['tipo','detalle'],
        classTr: ['det_row1','det_row2'],
        empty: 'empty_msg'
    });
    $('tipo').focus();
    val.addField("tipo","text",null,{'alias': 'Tipo','isNull': false});
    val.addField("detalle","text",null,{'alias': 'Detalle','isNull': false});
});

function save(){
    if(!val.valide()){
        Messages.valide(val);
    } else {       
        error = false;
        for(i=1;i<=mercurio06.getNumRows();i++){
            if(mercurio06.getRow(i)['tipo']==$F('tipo')){
                if(!mercurio06.isEdit()){
                    Messages.display(Array("El registro ya existe"),"warning");
                    error=true;
                    $('tipo').value='';
                    $('tipo').focus();    
                }       
            }
        }
        if(!error){
            mercurio06.save({
                afterSave: function(){
                    new Effect.Fade('edit_msg',{queue: 'end', scope: 'detalle'});
                }
            });
            $('tipo').enable();  
            $('tipo').focus();  
        }
    }
}
function removeRow(row){
    mercurio06.remove(row,{
        beforeRemove: function(elem){
            if(mercurio06.isEdit(elem)){
                Messages.display(Array("El registro actual esta en edicion"),"warning");
                return false;
            }
        }
    });
    $('tipo').focus();
}

function edit(e){
    $('tipo').disable(); 
    mercurio06.edit(e,{
        beforeEdit: function(){
            if(mercurio06.isEdit()){
                Messages.display(Array("Hay un registro en edicion"),"warning");
                return false;
            }
        },
        afterEdit: function(){
            new Effect.Appear('edit_msg',{queue: 'end', scope: 'detalle'});
        },
    });
    $('detalle').focus(); 
}

function saveIntro(evt,element){
    Bs.getKey(evt,{
        action: function(kc){
            if(kc==Event.KEY_RETURN) {
                save();
            }
        }
    });
}

function cancel(){
    $('tipo').enable(); 
    mercurio06.cancelEdit();
    new Effect.Fade('edit_msg',{queue: 'end', scope: 'detalle'});
    $('tipo').focus();
}
</script>

<div id="botones" align="right">
    <table>
        <tr>
            <td><?php echo Tag::image("guardar.png","title: Guardar","onclick: $('form').submit();","class: boton") ?></td>
            <td><?php echo Tag::image("reporte.png","title: Reporte","class: boton","onclick: reporte()") ?></td>
            <td><?php echo Tag::linkTo(Router::getController()."/index",Tag::image("exit.png","title: Cancelar","class: boton")) ?></td>
        </tr>
    </table>
</div>

<?php
 $width="500px";
 $rows=10;
 $field=4;
?>

<div>
    <table style="width: <?php echo $width ?>;">
        <tr>
            <td align="center" colspan="<?php echo $field ?>" height="30px">
                <div id="edit_msg" style="display: none; cursor: pointer; background-color: #DDFFDD" onclick="cancel();">
                    Registro en Edici&oacute;n (Click aqui para Cancelar)
                </div>
            </td>
        </tr>
        <tr>
            <td align="center"><?php echo Tag::textUpperField("tipo","maxlength: 2","size: 5","autocomplete: off","onkeydown: saveIntro(event,this);") ?> </td>
            <td align="center"><?php echo Tag::textUpperField("detalle","maxlength: 45","size: 45","autocomplete: off","onkeydown: saveIntro(event,this);") ?> </td>
            <td align="center" class="det_img"><?php echo Tag::image("Plus.png","title: Agregar Fila","onclick: save();") ?></td>
        </tr>
        <tr>
            <td align="center" class="titulos">Tipo</td>
            <td align="center" class="titulos">Detalle</td>
            <td>&nbsp;</td>
        </tr>
    </table>
</div>

<?php echo Tag::form(Router::getController()."/guardar", "id: form"); ?>
    <div id="capt_det" style="height: <?php echo ($rows*27)+($rows+2) ?>px;width: <?php echo $width ?>;">
        <table align="center" width="100%" cellpadding="0" cellspacing="1">
            <thead align="center">
                <tr id="empty_msg" style="display: <?php echo count($mercurio06)>0 ? 'none' : 'block' ?>;">
                    <td colspan="<?php echo $field ?>" align="center">No hay <?php echo $titulo; ?> que mostrar</td>
                </tr>
            </thead>
            <tbody>
        <?php if(!count($mercurio06)){ ?>
                <tr height="25px" ondblclick="edit(this);"  title="DobleClick para Editar">
                    <td class="tipo_" align="center" width="100px"></td>
                    <td class="detalle_" align="center" width="360px"></td>
                    <td class="det_img" align="center" width="40px"><?php echo Tag::image("Minus.png","title: Borrar Fila","onclick: removeRow(this.ancestors()[1])") ?></td>
                </tr>
        <?php } else {
                $i=0;
                foreach ($mercurio06 as $mmercurio06){ ?>
                <tr class="det_row<?php echo $i%2+1 ?>" height="25px" ondblclick="edit(this);"  title="DobleClick para Editar">
                    <td class="tipo_" align="center" width="100px"><?php echo Tag::hiddenField("tipo[]","value: {$mmercurio06->getTipo()}") ?><?php echo $mmercurio06->getTipo() ?></td>
                    <td class="detalle_" align="center" width="360px"><?php echo Tag::hiddenField("detalle[]","value: {$mmercurio06->getDetalle()}") ?><?php echo $mmercurio06->getDetalle() ?></td>
                    <td class="det_img" align="center" width="40px"><?php echo Tag::image("Minus.png","title: Borrar Fila","onclick: removeRow(this.ancestors()[1])") ?></td>
                </tr>
        <?php $i++; } } ?>
            </tbody>
        </table>
    </div>
<?php echo Tag::endForm() ?>
