<?php if($botones){ ?>
<div id="botones" align="right">
    <table>
        <tr>
            <td><?php echo Tag::image("reporte.png","title: Reporte","class: boton","onclick: reporte()") ?></td>
            <td><?php echo Tag::linkTo(Router::getController()."/index",Tag::image("exit.png","title: Salir","class: boton")) ?></td>
        </tr>
    </table>
</div>
<?php }

$field = 6;

if(count($gener->items)>0){ ?>
<div id="consulta" align="center" style="width: 650px;">
    <table align="center" width="100%" cellpadding='0' cellspacing='1'>
        <thead>
            <tr>
                <th width="25px">Documento</th>
                <th width="25px">Nombre</th>
                <th width="25px">Ciudad</th>
                <th width="25px">Telefono</th>
                <th width="25px">Direccion</th>
                <th width="25px">Estado</th>
            </tr>
        </thead>
        <?php $i=0; foreach($gener->items as $mgener){ ?>
            <tr class="td<?php echo $i%2+1 ?>">
                <?php if($solicitud == 'addempresa'){?>
                <td align="center" width="25px"><?php echo $mgener->getNit(); ?></td>
                <?php $mercurio07 = $Mercurio07->findFirst("documento = {$mgener->getNit()}")?>
                <td align="center" width="25px"><?php echo $mercurio07->getNombre(); ?></td>
                <td align="center" width="25px"><?php echo $mgener->getCodciu(); ?></td>
                <td align="center" width="25px"><?php echo $mgener->getDireccion(); ?></td>
                <td align="center" width="25px"><?php echo $mgener->getTelefono(); ?></td>
                <td align="center" width="25px"><?php echo $mgener->getEstado(); ?></td>
                <?php } ?>
            </tr>
        <?php $i++; } for($i=10-count($gener->items);$i>0;$i--){
            echo "<tr class='td".($i%2+1)."' height='25px'>";
            for($j=0;$j<$field;$j++) echo "<td></td>";
            echo "</tr>";
        } ?>
<?php echo Tag::hiddenField("codare","value: $solicitud");?>
        <tr>
            <td colspan="<?php echo $field ?>" align="right" style="border: none;">
                <?php echo $html; ?>
            </td>
        </tr>
    </table>
</div>
<?php } else { ?>
    No hay Resultados para la b&uacute;squeda.
<?php } ?>
