<?php echo View::getContent(); ?>

<script type="text/javascript">
    var val = new Validator();
    Event.observe(window, 'load',function(){
        val.addField("usuario","number",null,{'alias': 'Usuario','isNull': false});
        val.addField("cedtra","text",null,{'alias': 'Cedula','isNull': false});
        val.addField("nombre","text",null,{'alias': 'Nombre','isNull': false});
        val.addField("login","text",null,{'alias': 'Login','isNull': false});
        val.addField("tipfun","select",null,{'alias': 'Funcionario','isNull': false});
        val.addField("clave","text",null,{'alias': 'Clave','isNull': false,'doToUpperCase': false});
        val.addField("estado","select",null,{'alias': 'Estado','isNull': false});
        $('cedtra').focus();
        $('usuario').disable();
    });

    function Guardar(){
        if(!val.valide()){
            Messages.valide(val);
        }else{
            $('form').submit();
        }
    }
    
 </script>

<div id='botones' align='right'>
    <table>
        <tr>
            <td><?php echo Tag::image("guardar.png","title: Guardar","onclick: Guardar();","class: boton") ?></td>
            <td><?php echo Tag::linkTo(Router::getController()."/index",Tag::image("exit.png","title: Cancelar","class: boton")) ?></td>
        </tr>
    </table>
</div>

<?php echo Tag::form(Router::getController()."/guardar","id: form","autocomplete: off"); ?>
    <div align='center'>
        <table align='center'>
            <tr>
                <td align="right"><b>Usuario:</b></td>
                <td colspan="2"><?php echo Tag::numericField("usuario","size: 3","maxlength: 5") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Cedula:</b></td>
                <td align='left'><?php echo Tag::textUpperField("cedtra","size: 15","maxlength: 13") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Nombre:</b></td>
                <td align='left'><?php echo Tag::textUpperField("nombre","size: 30","maxlength: 35") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Login:</b></td>
                <td align='left'><?php echo Tag::textUpperField("login","size: 30","maxlength: 15") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Funcionario:</b></td>
                <td align='left'><?php echo Tag::select("tipfun",$Gener21->find(),"using: tipfun,detalle","use_dummy: true") ?></td>
            </tr>
            <tr>
                <td align="right"><b>Clave:</b></td>
                <td align="left"><?php echo Tag::passwordField("clave") ?></td>
            </tr>
            <tr>
                <td align='right'><b>Estado:</b></td>
                <td align='left'><?php echo Tag::selectStatic("estado",$Gener02->getEstadoArray(),"use_dummy: true") ?></td>
            </tr>
        </table>
    </div>
 <?php echo Tag::endForm() ?>
