<?php echo View::getContent(); ?>
<script type="text/javascript">
Event.observe(window,'load',function(){
    $('vista').setStyle({
        'width': '1000px',
        'marginLeft': '-40px'
      });
});

  function aprobar(x,elem){
    var com = confirm("Seguro de aprobar esta actualización?");
    if(com==false)return;
    //var motivo = prompt("Observaciones de la Actualizacion","");
    elem = elem.up();
    new Ajax.Request(Utils.getKumbiaURL("mercurio33/aprobar"), {
      parameters: {
        mid: x ,
        //motivo: motivo,
        tipo: '<?php echo $tipo; ?>' ,
      },
      onSuccess: function(transport){
        response = transport.responseText.evalJSON();
        if(response['flag']==true){
          elem.remove();
          Messagespro.display(Array(response['msg']),"success");
        }else{
          Messagespro.display(Array(response['msg']),"warning");
        }
      },
      onFailure: function(transport){
        alert(transport.responseText);
      }
    });
  }

  function rechazar(mid,elem){
    var com = confirm("Seguro de rechazar esta actualización?");
    if(com==false)return;
    var motivo = prompt("Motivo de Rechazo?","");
    if(motivo=="" || motivo==null){
        alert("Debe digitar un Motivo");
        return;
    }
    elem = elem.up();
    new Ajax.Request(Utils.getKumbiaURL("mercurio33/rechazar"), {
      parameters: {
        mid: mid,
        motivo: motivo
      },
      onSuccess: function(transport){
        var response = transport.responseText.evalJSON();
        if(response['flag']==true){
          elem.remove();
          Messagespro.display(Array(response['msg']),"success");
        }else{
          Messagespro.display(Array(response['msg']),"warning");
        }
      },
      onFailure: function(transport){
        alert(transport.responseText);
      }
    });
  }


</script>

<?php
	echo $html;
?>
